name: Deploy to VPS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create archive of repository
        run: |
          tar -czf deploy-package.tar.gz --exclude=".venv" --exclude=".database" --exclude=".git" --exclude=".github" .

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          source: "deploy-package.tar.gz"
          target: "/var/www/climb-grip-back"

      - name: Extract files and restart application on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd /var/www/climb-grip-back
            tar -xzf deploy-package.tar.gz -C /var/www/climb-grip-back
            source .venv/bin/activate
            pip install -r requirements.txt
            # Stop Gunicorn (if it's running)
            pgrep gunicorn | xargs kill -9 || true
            # Start Gunicorn
            gunicorn main:app --workers 3 --bind unix:climb-grip-back.sock --timeout 120 --worker-class uvicorn.workers.UvicornWorker --umask 007
            sudo systemctl restart nginx